!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  average_filter: false
  cartesian: true
  channel: 0
  edge_filter_threshold: 0
  frequency_modulation: 1
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      average_filter: false
      cartesian: true
      channel: 0
      edge_filter_threshold: 0
      frequency_modulation: 1
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      hdr_mode: 0
      id: 0
      image_type: 1
      integration_time_gray: 3000
      integration_time_tof_1: 60
      integration_time_tof_2: 480
      integration_time_tof_3: 1000
      interference_detection_limit: 0
      lens_center_offset_x: 0
      lens_center_offset_y: 0
      lens_type: 0
      median_filter: false
      min_amplitude: 70
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      publish_point_cloud: true
      roi_height: 240
      roi_left_x: 0
      roi_right_x: 319
      start_stream: true
      state: true
      temporal_filter_factor: 0.0
      temporal_filter_threshold: 0
      type: ''
      use_last_value: false
    state: []
  hdr_mode: 0
  image_type: 1
  integration_time_gray: 3000
  integration_time_tof_1: 60
  integration_time_tof_2: 480
  integration_time_tof_3: 1000
  interference_detection_limit: 0
  lens_center_offset_x: 0
  lens_center_offset_y: 0
  lens_type: 0
  median_filter: false
  min_amplitude: 70
  publish_point_cloud: true
  roi_height: 240
  roi_left_x: 0
  roi_right_x: 319
  start_stream: true
  temporal_filter_factor: 0.0
  temporal_filter_threshold: 0
  use_last_value: false
state: []
